// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVK7SbAzU9QR1SG4uMoas-hGgJSa4Q8zw',
    appId: '1:939151024179:web:34d7b12fcb80c46fd3c346',
    messagingSenderId: '939151024179',
    projectId: 'depertin-f940f',
    authDomain: 'depertin-f940f.firebaseapp.com',
    storageBucket: 'depertin-f940f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoi6_SF_oisaTPq4EJ7KUTRxlje1Sxg58',
    appId: '1:939151024179:android:53eb2f951a1a4f5cd3c346',
    messagingSenderId: '939151024179',
    projectId: 'depertin-f940f',
    storageBucket: 'depertin-f940f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIZRz0uPSig6G2sfE2H-u9fFaNxMkwm44',
    appId: '1:939151024179:ios:1da1607d301dfee5d3c346',
    messagingSenderId: '939151024179',
    projectId: 'depertin-f940f',
    storageBucket: 'depertin-f940f.firebasestorage.app',
    iosBundleId: 'com.example.depertinWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIZRz0uPSig6G2sfE2H-u9fFaNxMkwm44',
    appId: '1:939151024179:ios:1da1607d301dfee5d3c346',
    messagingSenderId: '939151024179',
    projectId: 'depertin-f940f',
    storageBucket: 'depertin-f940f.firebasestorage.app',
    iosBundleId: 'com.example.depertinWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVK7SbAzU9QR1SG4uMoas-hGgJSa4Q8zw',
    appId: '1:939151024179:web:860bc78282fec308d3c346',
    messagingSenderId: '939151024179',
    projectId: 'depertin-f940f',
    authDomain: 'depertin-f940f.firebaseapp.com',
    storageBucket: 'depertin-f940f.firebasestorage.app',
  );
}
